[package]
name = "gif-extract"
version = "0.1.0"
authors = ["Lucas W. <6264382+LucasWolschick@users.noreply.github.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
gif = "0.11.1"
png = "0.16.8"